mmitv_grid:
    resource: "@MMITVBundle/Controller/GridController.php"
    type:     annotation

mmitv_bloc:
    resource: "@MMITVBundle/Controller/BlocController.php"
    type:     annotation

mmitv_category:
    resource: "@MMITVBundle/Controller/CategoryController.php"
    type:     annotation

mmitv_video:
    resource: "@MMITVBundle/Controller/VideoController.php"
    type:     annotation

mmitv:
    resource: "@MMITVBundle/Resources/config/routing.yml"
    prefix:   /tv

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"