<?php

namespace MMI\TVBundle\Repository;

/**
 * BlocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOrderedBlocs($id)
    {
        $qb = $this->createQueryBuilder('b');

        $qb
            ->where('b.grid = :id')
            ->setParameter('id',$id)
            ->innerJoin('b.category','c')
            ->addSelect('c')
            ->addOrderBy('b.day','ASC')
            ->addOrderBy('b.slot','ASC')
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }

    public function getWithRelatedVideos($day,$slot,$grid)
    {
        $qb = $this->createQueryBuilder('b');

        $qb
            ->where('b.day = :day AND b.slot = :slot AND b.grid = :grid')
            ->setParameters(array('day'=>$day,'slot'=>$slot, 'grid'=>$grid))
            ->leftJoin('b.videos','v')
            ->addSelect('v')
            ->leftJoin('b.category','c')
            ->addSelect('c')
        ;

        return $qb
                ->getQuery()
                ->getSingleResult()
        ;
    }

    public function getOrderedBlocsWithVideos($id)
    {
        $qb = $this->createQueryBuilder('b');

        $qb
            ->where('b.grid = :id')
            ->setParameter('id',$id)
            ->innerJoin('b.category','c')
            ->addSelect('c')
            ->leftJoin('b.videos','v')
            ->addSelect('v')
            ->addOrderBy('b.day','ASC')
            ->addOrderBy('b.slot','ASC')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function getSingleBloc($slot,$day,$grid)
    {
        $qb = $this->createQueryBuilder('b');

        $qb
            ->where('b.grid = :grid AND b.day = :day AND b.slot = :slot')
            ->setParameters(array('grid'=>$grid, 'day'=>$day, 'slot'=>$slot))
            ->innerJoin('b.category','c')
            ->addSelect('c')
//            ->leftJoin('b.videos','v')
//            ->addSelect('v')
            ->addOrderBy('b.day','ASC')
            ->addOrderBy('b.slot','ASC')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }


}
