<?php

namespace MMI\TVBundle\Repository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNbRelatedVideos($id)
    {
        $qb = $this->createQueryBuilder('v');

        $qb ->innerJoin('v.category','c')
            ->addSelect('c')
            ->andWhere('c=:id')
            ->setParameter('id',$id)
            ->select('COUNT(v)')
        ;

        return $qb
            ->getQuery()
            ->getSingleScalarResult()
            ;
    }
}
