services:
#    mmitv.example:
#        class: MMI\TVBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    mmi_tv.renew.grid:
        class: MMI\TVBundle\Renew\MMIRenew
        arguments: ["@request_stack", "@doctrine.orm.entity_manager"]
