services:
#    mmitv.example:
#        class: MMI\TVBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    mmitv.renew.grid:
        class: MMI\TVBundle\MMIRenew\MMIRenew
        argument:
            - "@doctrine.orm.entity_manager"
